<?php

header("Access-Control-Allow-Origin: *");
header("Content-Type: application/json; charset=UTF-8");


    echo '

    {"records":[
      {
        "vid":"24",
        "nid":"24",
        "fid":"28",
        "title_format":"Podróż autobusem (loop, mono)",
        "play_count":"6772",
        "download_count":"2794",
        "downloadable":"1",
        "format":"1",
        "sample_rate":"44100",
        "channel_mode":"mono",
        "bitrate":"0",
        "bitrate_mode":"cbr",
        "playtime":"",
        "uid":"1",
        "filename":"soundimpress.plautobus_pks_od_wnetrza_silnik08110101.mp3",
        "filepath":"sites/default/files/audio/soundimpress.pl_autobus_pks_od_wnetrza_silnik08110101.mp3",
        "filemime":"audio/mpeg",
        "filesize":"1164166",
        "status":"1",
        "timestamp":"1225624564",
        "title":"Podróż autobusem (loop, mono)",
        "body":"Długie nagranie odgłosów jadącego autobusu z jego wnętrza.",
        "teaser":"Długie nagranie odgłosów jadącego autobusu z jego wnętrza.",
        "log":""
      },

      {
        "vid":"18",
        "nid":"18",
        "fid":"22",
        "title_format":"Świerszcz (loop, mono)",
        "play_count":"10968",
        "download_count":"6398",
        "downloadable":"1",
        "format":"1",
        "sample_rate":"44100",
        "channel_mode":"mono",
        "bitrate":"145781",
        "bitrate_mode":"vbr",
        "playtime":"0:19",
        "uid":"1",
        "filename":"soundimpress.plswierszcz_z_bliska_08110101.mp3",
        "filepath":"sites/default/files/audio/soundimpress.pl_swierszcz_z_bliska_08110101.mp3",
        "filemime":"audio/mpeg",
        "filesize":"348160",
        "status":"1",
        "timestamp":"1315825890",
        "title":"Świerszcz (loop, mono)",
        "body":"Świerszcz nagrany z małej odległości.",
        "teaser":"Świerszcz nagrany z małej odległości.",
        "log":""
      },

      {
        "vid":"17",
        "nid":"17",
        "fid":"21",
        "title_format":"Słowik (loop, mono)",
        "play_count":"11908",
        "download_count":"6483",
        "downloadable":"1",
        "format":"1",
        "sample_rate":"44100",
        "channel_mode":"mono",
        "bitrate":"136329",
        "bitrate_mode":"vbr",
        "playtime":"1:02",
        "uid":"1",
        "filename":"soundimpress.plptak_slowik(loop)08110101.mp3",
        "filepath":"sites/default/files/audio/soundimpress.pl_ptak_slowikloop08110101_0.mp3",
        "filemime":"audio/mpeg",
        "filesize":"1064144",
        "status":"1",
        "timestamp":"1225718432",
        "title":"Słowik (loop, mono)",
        "body":"Słowik kwilący w krzewie -  nagrany z dość małej odległości.",
        "teaser":"Słowik kwilący w krzewie -  nagrany z dość małej odległości.",
        "log":""
      },

      {
        "vid":"16",
        "nid":"16",
        "fid":"19",
        "title_format":"Las, Ptaki (loop, mono)",
        "play_count":"21167",
        "download_count":"8413",
        "downloadable":"1",
        "format":"1",
        "sample_rate":"44100",
        "channel_mode":"mono",
        "bitrate":"100833",
        "bitrate_mode":"vbr",
        "playtime":"0:29",
        "uid":"1",
        "filename":"soundimpress.pllas_ptaki(loop)08110101.mp3",
        "filepath":"sites/default/files/audio/soundimpress.pl_las_ptakiloop08110101.mp3",
        "filemime":"audio/mpeg",
        "filesize":"364544",
        "status":"1",
        "timestamp":"1225650370",
        "title":"Las, Ptaki (loop, mono)",
        "body":"Leśna, letnia aura dźwiękowa.",
        "teaser":"Leśna, letnia aura dźwiękowa.",
        "log":""
      },

      {
        "vid":"19",
        "nid":"19",
        "fid":"23",
        "title_format":"Gwarny plac (loop)",
        "play_count":"9715",
        "download_count":"3465",
        "downloadable":"1",
        "format":"1",
        "sample_rate":"44100",
        "channel_mode":"mono",
        "bitrate":"0",
        "bitrate_mode":"cbr",
        "playtime":"",
        "uid":"1",
        "filename":"soundimpress.plgwar_ludzie_plac_08110101.mp3",
        "filepath":"sites/default/files/audio/soundimpress.pl_gwar_ludzie_plac_08110101.mp3",
        "filemime":"audio/mpeg",
        "filesize":"239975",
        "status":"1",
        "timestamp":"1225624667",
        "title":"Gwarny plac (loop)",
        "body":"Gwarna atmosfera tworzona przez sporą grupę ludzi.",
        "teaser":"Gwarna atmosfera tworzona przez sporą grupę ludzi.",
        "log":""
      },

      {
        "vid":"20",
        "nid":"20",
        "fid":"24",
        "title_format":"Gwar, muzeum 1 (loop, stereo)",
        "play_count":"5037",
        "download_count":"2105",
        "downloadable":"1",
        "format":"1",
        "sample_rate":"44100",
        "channel_mode":"stereo",
        "bitrate":"0",
        "bitrate_mode":"cbr",
        "playtime":"",
        "uid":"1",
        "filename":"soundimpress.plgwar_muzeum_08110101.mp3",
        "filepath":"sites/default/files/audio/soundimpress.pl_gwar_muzeum_08110101.mp3",
        "filemime":"audio/mpeg",
        "filesize":"558042",
        "status":"1",
        "timestamp":"1225624600",
        "title":"Gwar, muzeum 1 (loop, stereo)",
        "body":"Gwarna atmosfera dużej ilości ludzi zwiedzających muzeum",
        "teaser":"Gwarna atmosfera dużej ilości ludzi zwiedzających muzeum",
        "log":""
      },

      {
        "vid":"21",
        "nid":"21",
        "fid":"25",
        "title_format":"Gwar, muzeum 2 (loop, stereo)",
        "play_count":"6377",
        "download_count":"2200",
        "downloadable":"1",
        "format":"1",
        "sample_rate":"44100",
        "channel_mode":"stereo",
        "bitrate":"0",
        "bitrate_mode":"cbr",
        "playtime":"",
        "uid":"1",
        "filename":"soundimpress.plgwar_muzeum_08110102.mp3",
        "filepath":"sites/default/files/audio/soundimpress.pl_gwar_muzeum_08110102.mp3",
        "filemime":"audio/mpeg",
        "filesize":"622825",
        "status":"1",
        "timestamp":"1225624709",
        "title":"Gwar, muzeum 2 (loop, stereo)",
        "body":"Gwarna atmosfera dużej ilości ludzi zwiedzających muzeum (inny wariant)",
        "teaser":"Gwarna atmosfera dużej ilości ludzi zwiedzających muzeum (inny wariant)",
        "log":""
      },

      {
        "vid":"22",
        "nid":"22",
        "fid":"26",
        "title_format":"Gwar - knajpa (loop, mono)",
        "play_count":"7473",
        "download_count":"3169",
        "downloadable":"1",
        "format":"1",
        "sample_rate":"44100",
        "channel_mode":"mono",
        "bitrate":"0",
        "bitrate_mode":"cbr",
        "playtime":"",
        "uid":"1",
        "filename":"soundimpress.plgwar_w_knajpie_rozmowy_08110101.mp3",
        "filepath":"sites/default/files/audio/soundimpress.pl_gwar_w_knajpie_rozmowy_08110101.mp3",
        "filemime":"audio/mpeg",
        "filesize":"1551949",
        "status":"1",
        "timestamp":"1225624589",
        "title":"Gwar - knajpa (loop, mono)",
        "body":"Knajpiany hałas, rozmowy zmieszane z podniesionymi i  podekscytowanymi głosami itp.",
        "teaser":"Knajpiany hałas, rozmowy zmieszane z podniesionymi i  podekscytowanymi głosami itp.",
        "log":""
      },

      {
        "vid":"23",
        "nid":"23",
        "fid":"27",
        "title_format":"Przejeżdzające auta (stereo)",
        "play_count":"6570",
        "download_count":"2890",
        "downloadable":"1",
        "format":"1",
        "sample_rate":"44100",
        "channel_mode":"stereo",
        "bitrate":"0",
        "bitrate_mode":"cbr",
        "playtime":"",
        "uid":"1",
        "filename":"soundimpress.plsamochody_przejezdzajace_stereo0811011.mp3",
        "filepath":"sites/default/files/audio/soundimpress.pl_samochody_przejezdzajace_stereo0811011.mp3",
        "filemime":"audio/mpeg",
        "filesize":"1090086",
        "status":"1",
        "timestamp":"1225624575",
        "title":"Przejeżdzające auta (stereo)",
        "body":"Przejeżdzające, pojedyncze auta osobowe.",
        "teaser":"Przejeżdzające, pojedyncze auta osobowe.",
        "log":""
      },

      {
        "vid":"87",
        "nid":"87",
        "fid":"99",
        "title_format":"Ostry grom (oneshot, stereo)",
        "play_count":"33920",
        "download_count":"17762",
        "downloadable":"1",
        "format":"1",
        "sample_rate":"44100",
        "channel_mode":"stereo",
        "bitrate":"160000",
        "bitrate_mode":"cbr",
        "playtime":"0:12",
        "uid":"1",
        "filename":"soundimpress_grom090701_4.mp3",
        "filepath":"sites/default/files/audio/soundimpress_grom090701_4.mp3",
        "filemime":"audio/mpeg",
        "filesize":"241664",
        "status":"1",
        "timestamp":"1246529342",
        "title":"Ostry grom (oneshot, stereo)",
        "body":"Ostry, łamliwy dźwięk, pobliskiego uderzenia pioruna",
        "teaser":"Ostry, łamliwy dźwięk, pobliskiego uderzenia pioruna",
        "log":""
      },

      {
        "vid":"25",
        "nid":"25",
        "fid":"29",
        "title_format":"Kroki po liściach (loop, mono)",
        "play_count":"5124",
        "download_count":"2308",
        "downloadable":"1",
        "format":"1",
        "sample_rate":"44100",
        "channel_mode":"mono",
        "bitrate":"128000",
        "bitrate_mode":"cbr",
        "playtime":"0:11",
        "uid":"1",
        "filename":"soundimpress.plkroki_na_lisciach0811011.mp3",
        "filepath":"sites/default/files/audio/soundimpress.pl_kroki_na_lisciach0811011.mp3",
        "filemime":"audio/mpeg",
        "filesize":"178953",
        "status":"1",
        "timestamp":"1225828603",
        "title":"Kroki po liściach (loop, mono)",
        "body":"Butami po liściach.",
        "teaser":"Butami po liściach.",
        "log":""
      },

      {
        "vid":"26",
        "nid":"26",
        "fid":"31",
        "title_format":"Kroki po lesie (loop, mono)",
        "play_count":"13676",
        "download_count":"4275",
        "downloadable":"1",
        "format":"1",
        "sample_rate":"44100",
        "channel_mode":"mono",
        "bitrate":"166555",
        "bitrate_mode":"vbr",
        "playtime":"0:11",
        "uid":"1",
        "filename":"soundimpress.plkroki_buty_w_lesie(loop)08110101.mp3",
        "filepath":"sites/default/files/audio/soundimpress.pl_kroki_buty_w_lesieloop08110101_0.mp3",
        "filemime":"audio/mpeg",
        "filesize":"233472",
        "status":"1",
        "timestamp":"1225649889",
        "title":"Kroki po lesie (loop, mono)",
        "body":"Buty na leśnej ścieżce",
        "teaser":"Buty na leśnej ścieżce",
        "log":""
      },

      {
        "vid":"27",
        "nid":"27",
        "fid":"33",
        "title_format":"Zapalniczka",
        "play_count":"7613",
        "download_count":"1973",
        "downloadable":"1",
        "format":"1",
        "sample_rate":"44100",
        "channel_mode":"mono",
        "bitrate":"0",
        "bitrate_mode":"cbr",
        "playtime":"",
        "uid":"1",
        "filename":"soundimpress.plzapalniczka_08110101.mp3",
        "filepath":"sites/default/files/audio/soundimpress.pl_zapalniczka_08110101_0.mp3",
        "filemime":"audio/mpeg",
        "filesize":"210944",
        "status":"1",
        "timestamp":"1225624610",
        "title":"Zapalniczka",
        "body":"Dźwięki zapalanej zapalniczki",
        "teaser":"Dźwięki zapalanej zapalniczki",
        "log":""
      },

      {
        "vid":"32",
        "nid":"32",
        "fid":"34",
        "title_format":"Czołg stoi (loop, mono)",
        "play_count":"6846",
        "download_count":"1890",
        "downloadable":"1",
        "format":"1",
        "sample_rate":"44100",
        "channel_mode":"mono",
        "bitrate":"136241",
        "bitrate_mode":"vbr",
        "playtime":"0:19",
        "uid":"1",
        "filename":"soundimpress.plczolg_silnik_stanie.mp3",
        "filepath":"sites/default/files/audio/soundimpress.pl_czolg_silnik_stanie.mp3",
        "filemime":"audio/mpeg",
        "filesize":"331776",
        "status":"1",
        "timestamp":"1225733545",
        "title":"Czołg stoi (loop, mono)",
        "body":"Silnik pojazdu czołgopodobnego na luzie.",
        "teaser":"Silnik pojazdu czołgopodobnego na luzie.",
        "log":""
      },

      {
        "vid":"33",
        "nid":"33",
        "fid":"35",
        "title_format":"Czołg - silnik gazuje (mono)",
        "play_count":"13511",
        "download_count":"3249",
        "downloadable":"1",
        "format":"1",
        "sample_rate":"44100",
        "channel_mode":"mono",
        "bitrate":"146122",
        "bitrate_mode":"vbr",
        "playtime":"0:25",
        "uid":"1",
        "filename":"soundimpress.plczolg_silnik_gazowanie.mp3",
        "filepath":"sites/default/files/audio/soundimpress.pl_czolg_silnik_gazowanie.mp3",
        "filemime":"audio/mpeg",
        "filesize":"466944",
        "status":"1",
        "timestamp":"1225733580",
        "title":"Czołg - silnik gazuje (mono)",
        "body":"Czołg rozgrzewający silnik i ruszający z kopyta.",
        "teaser":"Czołg rozgrzewający silnik i ruszający z kopyta.",
        "log":""
      }
    ]}

    ';



?>